DROP TABLE IF EXISTS FILMS, GENRE_FILMS, LIKE_FILMS, GENRE, MPA, FRIENDS, USERS CASCADE;

CREATE TABLE IF NOT EXISTS USERS
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(40) NOT NULL,
    login    varchar(40) NOT NULL,
    name     varchar(40) NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS FRIENDS
(
    friend_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_1        INTEGER REFERENCES USERS (user_id),
    user_2        INTEGER REFERENCES USERS (user_id),
    friend_status boolean
);

CREATE TABLE IF NOT EXISTS GENRE
(
    genre_id   INTEGER PRIMARY KEY,
    genre_name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA
(
    mpa_id   INTEGER PRIMARY KEY,
    mpa_name varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar(40) NOT NULL,
    description  varchar(150),
    release_date date,
    duration     int,
    mpa_id       INTEGER REFERENCES MPA (mpa_id),
    rate         int
);

CREATE TABLE IF NOT EXISTS GENRE_FILMS
(
    genre_films_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id        INTEGER REFERENCES FILMS (film_id),
    genre_id       INTEGER REFERENCES GENRE (genre_id)
);

CREATE TABLE IF NOT EXISTS LIKE_FILMS
(
    like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES FILMS (film_id),
    user_id INTEGER REFERENCES USERS (user_id)
)
